--------------------------------------------------------
--  Arquivo criado - quinta-feira-fevereiro-19-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NOTAS_FISCAIS_DETALHES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NOTAS_FISCAIS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTAS_FISCAIS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table NOTAS_FISCAIS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."NOTAS_FISCAIS" 
   (	"NOTA_FISCAL_ID" NUMBER DEFAULT "SCAN2SPEND"."NOTAS_FISCAIS_SEQ"."NEXTVAL", 
	"DATA" DATE, 
	"VALOR_TOTAL" FLOAT(126), 
	"USUARIO_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table NOTAS_FISCAIS_DETALHES
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" 
   (	"NOTA_FISCAL_DETALHE_ID" NUMBER DEFAULT "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES_SEQ"."NEXTVAL", 
	"PRODUTO" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"VALOR" FLOAT(126), 
	"VALOR_UNITARIO" FLOAT(126), 
	"UNIDADE_MEDIDA" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"VALOR_DESCONTO" FLOAT(126), 
	"QUANTIDADE" NUMBER(*,0), 
	"CREATED" DATE DEFAULT SYSDATE, 
	"NOTA_FISCAL_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES"."UNIDADE_MEDIDA" IS 'KG, MG, UN';
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."USUARIOS" 
   (	"USUARIO_ID" NUMBER(*,0) DEFAULT "SCAN2SPEND"."USUARIOS_SEQ"."NEXTVAL", 
	"NOME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOBRENOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SENHA" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED" DATE DEFAULT SYSDATE, 
	"UPDATED" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_DETALHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES_PK" ON "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" ("NOTA_FISCAL_DETALHE_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_PK" ON "SCAN2SPEND"."NOTAS_FISCAIS" ("NOTA_FISCAL_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."USUARIOS_PK" ON "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_BIU_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" 
BEFORE INSERT OR UPDATE ON USUARIOS 
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        :new.updated := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTAS_FISCAIS_DETALHES
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" MODIFY ("NOTA_FISCAL_DETALHE_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" MODIFY ("PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" MODIFY ("NOTA_FISCAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" ADD CONSTRAINT "NOTAS_FISCAIS_DETALHES_PK" PRIMARY KEY ("NOTA_FISCAL_DETALHE_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTAS_FISCAIS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" MODIFY ("NOTA_FISCAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" ADD CONSTRAINT "NOTAS_FISCAIS_PK" PRIMARY KEY ("NOTA_FISCAL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SOBRENOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_EMAIL_CK" CHECK (EMAIL LIKE '%@%') ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTAS_FISCAIS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" ADD CONSTRAINT "NOTAS_FISCAIS_USUARIO_FK" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTAS_FISCAIS_DETALHES
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES" ADD CONSTRAINT "NOTAS_FISCAIS_DETALHES_NOTAS_FISCAIS_FK" FOREIGN KEY ("NOTA_FISCAL_ID")
	  REFERENCES "SCAN2SPEND"."NOTAS_FISCAIS" ("NOTA_FISCAL_ID") ENABLE;
