--------------------------------------------------------
--  Arquivo criado - terça-feira-março-03-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NOTA_FISCAL_ITENS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTA_FISCAL_ITENS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 111 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NOTAS_FISCAIS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTAS_FISCAIS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."USUARIOS" 
   (	"USUARIO_ID" NUMBER(*,0) DEFAULT "SCAN2SPEND"."USUARIOS_SEQ"."NEXTVAL", 
	"NOME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOBRENOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SENHA" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED" DATE DEFAULT SYSDATE, 
	"UPDATED" DATE, 
	"ATIVO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."USUARIOS_PK" ON "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_BIU_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" 
BEFORE INSERT OR UPDATE ON USUARIOS 
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        :new.updated := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SOBRENOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_EMAIL_CK" CHECK (EMAIL LIKE '%@%') ENABLE;
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("ATIVO" NOT NULL ENABLE);
