--------------------------------------------------------
--  Arquivo criado - sexta-feira-março-27-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence NOTA_FISCAL_ITENS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTA_FISCAL_ITENS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 329 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NOTAS_FISCAIS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."NOTAS_FISCAIS_SEQ"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 142 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIOS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SCAN2SPEND"."USUARIOS_SEQ"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 34 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table NOTA_FISCAL_ITENS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" 
   (	"NOTA_FISCAL_ITEM_ID" NUMBER DEFAULT "SCAN2SPEND"."NOTA_FISCAL_ITENS_SEQ"."NEXTVAL", 
	"PRODUTO" VARCHAR2(250 BYTE) COLLATE "USING_NLS_COMP", 
	"VALOR" FLOAT(126), 
	"VALOR_UNITARIO" FLOAT(126), 
	"UNIDADE_MEDIDA" CHAR(2 BYTE) COLLATE "USING_NLS_COMP", 
	"VALOR_DESCONTO" FLOAT(126), 
	"QUANTIDADE" NUMBER(*,0), 
	"CREATED" DATE DEFAULT SYSDATE, 
	"NOTA_FISCAL_ID" NUMBER, 
	"ATIVO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S', 
	"CATEGORIA" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;

   COMMENT ON COLUMN "SCAN2SPEND"."NOTA_FISCAL_ITENS"."UNIDADE_MEDIDA" IS 'KG, MG, UN';
--------------------------------------------------------
--  DDL for Table NOTAS_FISCAIS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."NOTAS_FISCAIS" 
   (	"NOTA_FISCAL_ID" NUMBER DEFAULT "SCAN2SPEND"."NOTAS_FISCAIS_SEQ"."NEXTVAL", 
	"DATA" DATE, 
	"VALOR_TOTAL" FLOAT(126), 
	"USUARIO_ID" NUMBER, 
	"ATIVO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S', 
	"DESCONTO" FLOAT(126)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "SCAN2SPEND"."USUARIOS" 
   (	"USUARIO_ID" NUMBER(*,0) DEFAULT "SCAN2SPEND"."USUARIOS_SEQ"."NEXTVAL", 
	"NOME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SOBRENOME" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"EMAIL" VARCHAR2(150 BYTE) COLLATE "USING_NLS_COMP", 
	"SENHA" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATED" DATE DEFAULT SYSDATE, 
	"UPDATED" DATE, 
	"ATIVO" CHAR(1 BYTE) COLLATE "USING_NLS_COMP" DEFAULT 'S'
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_DETALHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES_PK" ON "SCAN2SPEND"."NOTA_FISCAL_ITENS" ("NOTA_FISCAL_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_PK" ON "SCAN2SPEND"."NOTAS_FISCAIS" ("NOTA_FISCAL_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."USUARIOS_PK" ON "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_DETALHES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_DETALHES_PK" ON "SCAN2SPEND"."NOTA_FISCAL_ITENS" ("NOTA_FISCAL_ITEM_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NOTAS_FISCAIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."NOTAS_FISCAIS_PK" ON "SCAN2SPEND"."NOTAS_FISCAIS" ("NOTA_FISCAL_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCAN2SPEND"."USUARIOS_PK" ON "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_BIU_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" 
BEFORE INSERT OR UPDATE ON USUARIOS 
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        :new.updated := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USUARIOS_BIU_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" 
BEFORE INSERT OR UPDATE ON USUARIOS 
FOR EACH ROW
BEGIN
    IF UPDATING THEN
        :new.updated := SYSDATE;
    END IF;
END;
/
ALTER TRIGGER "SCAN2SPEND"."USUARIOS_BIU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Package PKG_AUTH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCAN2SPEND"."PKG_AUTH" AS 

    FUNCTION encrypt_pwd(
        p_password IN VARCHAR2
    ) RETURN VARCHAR2;
    
    
    PROCEDURE auth(
        p_login      IN  VARCHAR2,
        p_senha      IN  VARCHAR2,
        P_usuario_id OUT NUMBER
    );
    
    
    PROCEDURE post_auth(
        p_usuario_id IN NUMBER,
        p_nome       OUT VARCHAR2,
        p_sobrenome  OUT VARCHAR2,
        p_email      OUT VARChAR2
    );

END PKG_AUTH;

/
--------------------------------------------------------
--  DDL for Package Body PKG_AUTH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCAN2SPEND"."PKG_AUTH" AS

    FUNCTION encrypt_pwd(
        p_password IN VARCHAR2
    ) RETURN VARCHAR2
    IS
    BEGIN
        RETURN LOWER(
            RAWTOHEX(
                DBMS_CRYPTO.HASH(
                    UTL_I18N.STRING_TO_RAW(p_password, 'AL32UTF8'),
                    DBMS_CRYPTO.HASH_SH256
                )
            )
        );
    END;
    
    PROCEDURE auth(
        p_login      IN  VARCHAR2,
        p_senha      IN  VARCHAR2,
        P_usuario_id OUT NUMBER
    ) IS 
        CURSOR c_usuario IS
            SELECT
                usuario_id as id
            FROM
                usuarios
            WHERE 
                UPPER(email) = UPPER(p_login)
            AND senha = encrypt_pwd(p_senha);
            
        r_usuario c_usuario%ROWTYPE;
    BEGIN
        
        OPEN c_usuario;
        FETCH c_usuario INTO r_usuario;
        
        IF c_usuario%FOUND THEN 
            p_usuario_id := r_usuario.id;
        END IF;
        
        CLOSE c_usuario;
    
    EXCEPTION
        WHEN OTHERS THEN 
            raise_application_error(-20001, 'Erro ao validar credenciais de login do usuário');

    END;
    
    PROCEDURE post_auth(
        p_usuario_id IN NUMBER,
        p_nome       OUT VARCHAR2,
        p_sobrenome  OUT VARCHAR2,
        p_email      OUT VARChAR2
    ) IS 
        CURSOR c_usuario IS
            SELECT
                nome,
                sobrenome,
                email
            FROM
                usuarios
            WHERE 
                usuario_id = p_usuario_id;
        
        r_usuario c_usuario%ROWTYPE;
        
    BEGIN
        
        OPEN c_usuario;
        FETCH c_usuario INTO r_usuario;
        
        IF c_usuario%FOUND THEN
            p_nome := r_usuario.nome;
            p_sobrenome := r_usuario.sobrenome;
            p_email := r_usuario.email;
        END IF;
        
        CLOSE c_usuario;
    
    EXCEPTION
        WHEN OTHERS THEN 
            raise_application_error(-20001, 'Erro ao retornar informações do usuário');
    
    END;

END pkg_auth;

/
--------------------------------------------------------
--  Constraints for Table NOTA_FISCAL_ITENS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("NOTA_FISCAL_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("NOTA_FISCAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" ADD CONSTRAINT "NOTAS_FISCAIS_DETALHES_PK" PRIMARY KEY ("NOTA_FISCAL_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" MODIFY ("ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTAS_FISCAIS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" MODIFY ("NOTA_FISCAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" ADD CONSTRAINT "NOTAS_FISCAIS_PK" PRIMARY KEY ("NOTA_FISCAL_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" MODIFY ("ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("USUARIO_ID" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SOBRENOME" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("USUARIO_ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "SCAN2SPEND"."USUARIOS" ADD CONSTRAINT "USUARIOS_EMAIL_CK" CHECK (EMAIL LIKE '%@%') ENABLE;
  ALTER TABLE "SCAN2SPEND"."USUARIOS" MODIFY ("ATIVO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NOTA_FISCAL_ITENS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTA_FISCAL_ITENS" ADD CONSTRAINT "NOTAS_FISCAIS_DETALHES_NOTAS_FISCAIS_FK" FOREIGN KEY ("NOTA_FISCAL_ID")
	  REFERENCES "SCAN2SPEND"."NOTAS_FISCAIS" ("NOTA_FISCAL_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTAS_FISCAIS
--------------------------------------------------------

  ALTER TABLE "SCAN2SPEND"."NOTAS_FISCAIS" ADD CONSTRAINT "NOTAS_FISCAIS_USUARIO_FK" FOREIGN KEY ("USUARIO_ID")
	  REFERENCES "SCAN2SPEND"."USUARIOS" ("USUARIO_ID") ENABLE;
